name: advent_of_code_2022
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  collection:
  quiver:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
